# Generated by Django 3.2.7 on 2021-09-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leve',
            new_name='Level',
        ),
    ]
