# Generated by Django 3.2.7 on 2021-10-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='function_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.function'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='option',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.level'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category1', to='api.category'),
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=30)),
                ('subcategory_details', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='api.category')),
            ],
        ),
    ]
