# Generated by Django 3.2.7 on 2021-10-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211011_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_tag',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='function',
            name='function_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='score_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='subcategory_name',
            field=models.CharField(max_length=50),
        ),
    ]
